export default {
  products: [
    {
      _id: '689539',
      imageUrl: '../images/Jax ACN-07HE.jpg',
      title: 'Cплит-система Jax ACN-07HE',
      price: 14280,
      countInStock: 1,
      type: 'standart',
      inverter: 'Нет',
      led: 'Есть',
      warranty: '12 месяцев',
      wifi: 'Нет',
      area: '21',
      power: '2.1 кВт',
      modes: 'Автоочистка, Осушение, Ночной режим',
      country: 'КНР',
      brand: 'JAX',
      manufacturer: 'Haier',
      sizeInner: '700х260х200',
      sizeOuter: '696х432х256',
      weight: '7,4/21,6',
      compressor: 'QingAn',
      noiseInner: '22-34',
      noiseOuter: '52',
      diameterPipes: '6,35 (1/4)/9,52 (3/8)',
      energyClass: 'A',
      refrigerant: 'R410',
      description:
        'Jax серии Tasmania - современная сплит-система от достойной австралийской торговой марки. Изделие может похвастать эффективностью в работе и скромным потреблением электроэнергии. Среди прочих режимов предусмотрен ночной режим работы с минимальными шумовыми характеристиками. Сплит-системы оснащены фильтрами очистки воздуха и встроенным ионизатором.',
    },
    {
      _id: '699415',
      imageUrl: '../images/Lanzkraft LSWH-20FC1NLSAH-20FC1N.webp',
      title: 'Cплит-система Lanzkraft Simple on-off LSWH-20FC1N/LSAH-20FC1N',
      price: 30000,
      countInStock: 2,
      type: 'standart',
      inverter: 'Нет',
      warranty: '36 месяцев',
      wifi: 'Нет',
      area: '20',
      rangeArea: '699415',
      volume: '26-38',
      power: '2.05 кВт',
      modes: 'Обогрев, Осушение, Охлаждение',
      country: 'КНР',
      brand: 'Lanzkraft',
      manufacturer: 'Changhong',
    },
    {
      _id: '1114842',
      imageUrl: 'https://via.placeholder.com/150',
      title: 'Сплит-система инверторного типа BALLU BSLI-07HN1/EE/EU_20Y комплект',
      price: 43660,
      countInStock: 4,
      type: 'inverter',
      inverter: 'Да',
      warranty: '3 года',
      wifi: 'Нет',
      area: '22',
      rangeArea: '1114842',
      volume: '23',
      power: '1114842',
      modes: 'undefined,Режим обогрева,Режим осушения',
      country: 'turkey',
      brand: 'BALLU',
      manufacturer: 'Haier',
    },
    {
      _id: '1114844',
      imageUrl: 'https://via.placeholder.com/368.33x205/d6dcff',
      title: 'Сплит-система BALLU BSAG-09HN1_20Y комплект',
      price: 35280,
      countInStock: 1,
      type: 'standart',
      inverter: 'Нет',
      warranty: '3 года',
      wifi: 'Нет',
      area: '25',
      rangeArea: '1114844',
      volume: '25',
      power: '1114844',
      modes: 'Режим автоочистки,Режим обогрева,Режим осушения',
      country: 'turkey',
      brand: 'BALLU',
      manufacturer: 'Haier',
    },
    {
      _id: '1114855',
      imageUrl: 'https://via.placeholder.com/368.33x205/d6dcff',
      title: 'Сплит-система инверторного типа BALLU BSLI-12HN1/EE/EU_20Y комплект',
      price: 52390,
      countInStock: 3,
      type: 'inverter',
      inverter: 'Да',
      warranty: '3 года',
      wifi: 'Нет',
      area: '32',
      rangeArea: '1114855',
      volume: '26',
      power: '1114855',
      modes: 'undefined,Режим обогрева,Режим осушения',
      country: 'turkey',
      brand: 'BALLU',
      manufacturer: 'Haier',
    },
    {
      _id: '1114861',
      imageUrl: 'https://via.placeholder.com/368.33x205/d6dcff',
      title: 'Сплит-система BALLU BSAG-24HN1_20Y комплект',
      price: 90830,
      countInStock: 3,
      type: 'standart',
      inverter: 'Нет',
      warranty: '3 года',
      wifi: 'Нет',
      area: '70',
      rangeArea: '1114861',
      volume: '35',
      power: '1114861',
      modes: 'Режим автоочистки,Режим обогрева,Режим осушения',
      country: 'turkey',
      brand: 'BALLU',
      manufacturer: 'Haier',
    },
    {
      _id: '1114868',
      imageUrl: 'https://via.placeholder.com/368.33x205/d6dcff',
      title: 'Сплит-система BALLU BSD-07HN1_20Y комплект',
      price: 31720,
      countInStock: 5,
      type: 'standart',
      inverter: 'Нет',
      warranty: '3 года',
      wifi: 'Нет',
      area: '22',
      rangeArea: '1114868',
      volume: '23',
      power: '1114868',
      modes: 'Режим автоочистки,Режим обогрева,Режим осушения',
      country: 'china',
      brand: 'BALLU',
      manufacturer: 'Haier',
    },
    {
      _id: '1114870',
      imageUrl: 'https://via.placeholder.com/368.33x205/d6dcff',
      title: 'Сплит-система BALLU BSAG-12HN1_20Y комплект',
      price: 46240,
      countInStock: 2,
      type: 'standart',
      inverter: 'Нет',
      warranty: '3 года',
      wifi: 'Нет',
      area: '32',
      rangeArea: '1114870',
      volume: '30',
      power: '1114870',
      modes: 'Режим автоочистки,Режим обогрева,Режим осушения',
      country: 'china',
      brand: 'BALLU',
      manufacturer: 'Haier',
    },
  ],
};
